# Generated by Django 4.0.2 on 2022-02-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
